-- Criação do Banco de Dados

CREATE DATABASE DataBaseHospital;

-- Usando o Banco de Dados

use DataBaseHospital;

-- Criando Tabelas das Entidades

CREATE TABLE Medico (
CPF_MED VARCHAR(12) PRIMARY KEY NOT NULL,
CRM VARCHAR(20),
RG_MED VARCHAR (12),
NOME_MED VARCHAR(100),
DATA_NASCI_MED DATE NOT NULL,
ENDERECO_MED VARCHAR(50),
TELEFONE_MED VARCHAR(12),
EMAIL_MED VARCHAR(320)
);

CREATE TABLE Especialidade (
ID_ESPECIALIDADE SERIAL PRIMARY KEY,
NOME_ESPECIALIDADE VARCHAR(20)
);

CREATE TABLE Paciente (
CPF_PAC VARCHAR(12) PRIMARY KEY NOT NULL,
RG_PAC VARCHAR(12),
NOME_PAC VARCHAR(100),
DATA_NASCI_PAC DATE NOT NULL,
ENDERECO_PAC VARCHAR(50),
TELEFONE_PAC VARCHAR(12),
EMAIL_PAC VARCHAR(320)
);

CREATE TABLE Convenio (
ID_CONVENIO SERIAL PRIMARY KEY,
NOME_CONV VARCHAR(20),
CNPJ VARCHAR(20),
TEMPO_CARENCIA VARCHAR(10)
);

CREATE TABLE Consulta (
ID_CONSULTA SERIAL PRIMARY KEY,
DATA_CONSULTA DATE NOT NULL,
HORARIO TIME NOT NULL,
VALOR_CONSUL DOUBLE NOT NULL DEFAULT 0.00,
NUM_CARTEIRA INT,
FOREIGN KEY(CRM) REFERENCES Medico(CRM),
FOREIGN KEY(CPF_PAC) REFERENCES Paciente(CPF_PAC),
FOREIGN KEY(NOME_CONV) REFERENCES Convenio(NOME_CONV)
);

CREATE TABLE Receita (
ID_RECEITA SERIAL PRIMARY KEY,
MEDICAMENTO_REC VARCHAR(20),
QUANTIDADE_MED VARCHAR(3),
INSTRUCAO_MED VARCHAR(50)
);

CREATE TABLE Recebimento (
    ID_RECEBIMENTO INT PRIMARY KEY,
    DATA_RECEBIMENTO DATE NOT NULL
);


CREATE TABLE Recebimento_Email (
    ID_RECEBIMENTO INT PRIMARY KEY,
    EMAIL VARCHAR(320),
    FOREIGN KEY (ID_RECEBIMENTO) REFERENCES Recebimento(ID_RECEBIMENTO)
);

CREATE TABLE Recebimento_Impresso (
    ID_RECEBIMENTO INT PRIMARY KEY,
    FOREIGN KEY (ID_RECEBIMENTO) REFERENCES Recebimento(ID_RECEBIMENTO)
);

CREATE TABLE Enfermeiro (
CPF_ENF VARCHAR(12) PRIMARY KEY NOT NULL,
NOME_ENF VARCHAR(100),
COREN VARCHAR(20)
);

CREATE TABLE Internacao (
ID_INTERNACAO SERIAL PRIMARY KEY,
DATA_ENTRADA DATE NOT NULL,
DATA_PREV_ALTA DATE NOT NULL,
DATA_ALTA DATE NOT NULL,
PROCEDIMENTO VARCHAR(300),
FOREIGN KEY(COREN) REFERENCES Enfermeiro(COREN),
FOREIGN KEY(CPF_PAC) REFERENCES Paciente(CPF_PAC)
);

CREATE TABLE Quarto (
ID_QUARTO SERIAL PRIMARY KEY,
NUMERO VARCHAR(3),
TIPO VARCHAR(20)
);

CREATE TABLE Tipo_Quarto (
ID_TIPO_QUARTO SERIAL PRIMARY KEY,
VALOR_DIARIA DOUBLE NOT NULL DEFAULT 0.00,
DESCRICAO_QUARTO VARCHAR(30)
);